import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import josephSophia from 'next/font/local';
import "./globals.css";

const josephsophia = josephSophia({
  src: [
    {
      path: './fonts/josephsophia/josephsophia.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-joseph-sophia',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josephsophia.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
